runtime: python27
api_version: 1
threadsafe: true

handlers:

# Fonts, images, media
- url: /(.+\.(woff|obj|gif|ico|jpe?g|png|svgz?|ogg|mp3))
  static_files: dist/\1
  upload: dist/(.+\.(woff|obj|gif|ico|jpe?g|png|svgz?|ogg|mp3))

# CSS, Javascript, text and other file types
- url: /(.+\.(css|js|xml|txt|json|md))
  static_files: dist/\1
  upload: dist/(.+\.(css|js|xml|txt|json|md))

# all other requests, get index.html
- url: /(.*)
  static_files: dist/index.html
  upload: dist/index.html
  secure: always

skip_files:
- ^(.*/)?\..*$
- package.json
- ^node_modules/(.*/)?
- \.gitignore
- ^\.git/.*
- (.*).DS_Store
- ^src/(.*/)?
- ^README\..*
- ^webpack.config\.js