runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: dist/index.html
  upload: dist/index.html
  login: admin
  secure: always

- url: /(.*)
  static_files: dist/\1
  upload: dist/(.*)
  secure: always

skip_files:
- ^(.*/)?\..*$
- package.json
- ^node_modules/(.*/)?
- \.gitignore
- ^\.git/.*
- (.*).DS_Store
- ^src/(.*/)?
- ^README\..*
- ^webpack.config\.js